spring:
  #配置数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///stone_blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    #druid数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 5
    maxWait: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
#配置日志
logging:
  level:
    #全局级别
    root: info
    #针对指定包的级别
    com.djn: debug
  #指定日志存放路径
  file:
    name: logs/stone-dev.log
#配置访问路径的项目名
server:
  servlet:
    context-path: /stone
#整合mybatis配置
mybatis:
  type-aliases-package: com.djn.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
